---
local:
  hosts:
    localhost:
      gather_facts: false
      ansible_connection: "local"

lxd_hosts:
  hosts:
    mannerheim:
      gather_facts: false
      ansible_host: "95.216.214.17"
      ansible_port: "61337"
      ansible_user: "root"
      ansible_ssh_private_key_file: "~/.ssh/id_ed25519_2022"


lxd_containers:
  hosts:
    pixelfed:
      gather_facts: false
      parent: "mannerheim"
      timezone: "Europe/Stockholm"
      packages: ['plocate']
      profiles: ['default']
      present: true
      alias: "ubuntu/jammy/cloud"
      ip: "10.13.37.22/24"
      dns: "1.1.1.1"
      cpu: 4
      mem: "4GB"
      mem_enforce: "soft"
      authorized_keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOqS6wj7my4ayCttn1woZFqavmI2ELJVqdQksYB25/Ag linus@agren.cc"