---
local:
  hosts:
    localhost:
      gather_facts: false
      ansible_connection: "local"

lxd_hosts:
  hosts:
#    mannerheim:
#      gather_facts: false
#      ansible_host: "95.216.214.17"
#      ansible_port: "61337"
#      ansible_user: "root"
#      ansible_ssh_private_key_file: "~/.ssh/id_ed25519_2022"
#      zfs_pool: ""
    kuznetsov:
      gather_facts: false
      ansible_host: "79.136.1.125"
      ansible_port: "22"
      ansible_user: "ubuntu"
      ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
      zfs_pool: "tank/lxd"

lxd_containers:
  hosts:
    mysql:
      gather_facts: false
      parent: "kuznetsov"
      timezone: "Europe/Stockholm"
      packages: ['plocate', 'ssh', 'mysql-server', 'htop']
      profiles: "default"
      present: true
      alias: "ubuntu/jammy/cloud"
      ip: "10.13.37.10/24"
      dns: "1.1.1.1"
      cpu: 4
      mem: "4GB"
      mem_enforce: "soft"
      authorized_keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOqS6wj7my4ayCttn1woZFqavmI2ELJVqdQksYB25/Ag linus@agren.cc"
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINSki+Juy0QywKsyNNyc1O/KwYFPDgT14GYGQYttcuIR linus.agren@bahnhof.net"
    checkmk:
      gather_facts: false
      parent: "kuznetsov"
      timezone: "Europe/Stockholm"
      packages: ['plocate', 'ssh', 'htop', 'btop']
      profiles: "default"
      present: true
      alias: "ubuntu/jammy/cloud"
      ip: "10.13.37.20/24"
      dns: "1.1.1.1"
      cpu: 4
      mem: "4GB"
      mem_enforce: "soft"
      authorized_keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOqS6wj7my4ayCttn1woZFqavmI2ELJVqdQksYB25/Ag linus@agren.cc"
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINSki+Juy0QywKsyNNyc1O/KwYFPDgT14GYGQYttcuIR linus.agren@bahnhof.net"
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDLGrckzF1pPXxygf5OrnP5xKFcsIBer0FtvpERnd2vw simon.ledam@bahnhof.net"
    checkmkclient:
      gather_facts: false
      parent: "kuznetsov"
      timezone: "Europe/Stockholm"
      packages: ['plocate', 'ssh', 'htop', 'btop']
      profiles: "default"
      present: true
      alias: "ubuntu/jammy/cloud"
      ip: "10.13.37.30/24"
      dns: "1.1.1.1"
      cpu: 4
      mem: "4GB"
      mem_enforce: "soft"
      authorized_keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOqS6wj7my4ayCttn1woZFqavmI2ELJVqdQksYB25/Ag linus@agren.cc"
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINSki+Juy0QywKsyNNyc1O/KwYFPDgT14GYGQYttcuIR linus.agren@bahnhof.net"
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDLGrckzF1pPXxygf5OrnP5xKFcsIBer0FtvpERnd2vw simon.ledam@bahnhof.net"