---
# begin by creating local files:
#
# - cloudconfig.yml containing user-data and network-config for *all*
#   containers, passed in upon creation
#
# - ssh_config loaded by ansible to understand how to reach all nodes
#

- name: "Create initial files locally"
  hosts: localhost
  roles: ['localhost']

# apply the 'lxd_host' role to group lxd_hosts. this ensures LXD is
# installed and bootstrapped, and ensures all containers referring to
# the host as 'parent' exist, and otherwise creates them

- name: "Set up lxd_hosts and containers"
  hosts: "lxd_hosts"
  become: true
  vars_files:
    - cloudconfig.yml
  roles: ['lxd_host']

- name: "Set up postgres"
  hosts: "postgres"
  become: true
#  vars:
#    - postgres_databases: "{{ postgres_databases }}"
  roles: ['postgres']

#- name: "Set up etherpad_containers"
#  hosts: "etherpad_containers"
#  become: true
#  roles:
#    - etherpad_container

# Skipped
#- name: "Set up prometheus"
#  hosts: "prometheus_containers"
#  roles:
#    - prometheus

#- name: "Set up nginx forwarding for lxd"
#  become: true
#  hosts: "lxd_hosts"
#  roles:
#    - lxd_host_nginx_forwarder
#