- name: "Generate cloud-config"
  ansible.builtin.template:
    src: "cloudconfig.j2"
    dest: "cloudconfig.yml"

- name: "Generate ssh_config"
  ansible.builtin.template:
    src: "ssh_config.j2"
    dest: "ssh_config"